name: Publish

on:
  workflow_run:
    workflows: ["Release"]
    types: 
      - completed

jobs:
  publishJob:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      VERSION: 0
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Set Version
        uses: actions/checkout@v2
      - run: |
            VER=$(cat package.json | grep version | head | awk '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
            echo "::set-env name=VERSION::$VER"
      - name: Switch Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ format('release-{0}', env.VERSION) }}
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{env.VERSION}}
      - name: Deploy to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
