name: Test

on: push

jobs:
  pushJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Lint and Test 
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Send to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
