"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.retrieveFromSessionStorage = exports.retrieveFromLocalStorage = exports.removeFromSessionStorage = exports.removeFromLocalStorage = exports.clearSessionStorage = exports.clearLocalStorage = exports.addToSessionStorage = exports.addToLocalStorage = exports.retrieveFromStorage = exports.removeFromStorage = exports.deleteStorage = exports.createNewStorage = exports.clearStorage = exports.addToStorage = void 0;
const customStorage_1 = require("./customStorage");
Object.defineProperty(exports, "addToStorage", { enumerable: true, get: function () { return customStorage_1.addToStorage; } });
Object.defineProperty(exports, "clearStorage", { enumerable: true, get: function () { return customStorage_1.clearStorage; } });
Object.defineProperty(exports, "createNewStorage", { enumerable: true, get: function () { return customStorage_1.createNewStorage; } });
Object.defineProperty(exports, "deleteStorage", { enumerable: true, get: function () { return customStorage_1.deleteStorage; } });
Object.defineProperty(exports, "removeFromStorage", { enumerable: true, get: function () { return customStorage_1.removeFromStorage; } });
Object.defineProperty(exports, "retrieveFromStorage", { enumerable: true, get: function () { return customStorage_1.retrieveFromStorage; } });
const webStorage_1 = require("./webStorage");
Object.defineProperty(exports, "addToLocalStorage", { enumerable: true, get: function () { return webStorage_1.addToLocalStorage; } });
Object.defineProperty(exports, "addToSessionStorage", { enumerable: true, get: function () { return webStorage_1.addToSessionStorage; } });
Object.defineProperty(exports, "clearLocalStorage", { enumerable: true, get: function () { return webStorage_1.clearLocalStorage; } });
Object.defineProperty(exports, "clearSessionStorage", { enumerable: true, get: function () { return webStorage_1.clearSessionStorage; } });
Object.defineProperty(exports, "removeFromLocalStorage", { enumerable: true, get: function () { return webStorage_1.removeFromLocalStorage; } });
Object.defineProperty(exports, "removeFromSessionStorage", { enumerable: true, get: function () { return webStorage_1.removeFromSessionStorage; } });
Object.defineProperty(exports, "retrieveFromLocalStorage", { enumerable: true, get: function () { return webStorage_1.retrieveFromLocalStorage; } });
Object.defineProperty(exports, "retrieveFromSessionStorage", { enumerable: true, get: function () { return webStorage_1.retrieveFromSessionStorage; } });
