"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const customStorage_1 = require("./customStorage");
exports.addToStorage = customStorage_1.addToStorage;
exports.clearStorage = customStorage_1.clearStorage;
exports.createNewStorage = customStorage_1.createNewStorage;
exports.deleteStorage = customStorage_1.deleteStorage;
exports.removeFromStorage = customStorage_1.removeFromStorage;
exports.retrieveFromStorage = customStorage_1.retrieveFromStorage;
const webStorage_1 = require("./webStorage");
exports.addToLocalStorage = webStorage_1.addToLocalStorage;
exports.addToSessionStorage = webStorage_1.addToSessionStorage;
exports.clearLocalStorage = webStorage_1.clearLocalStorage;
exports.clearSessionStorage = webStorage_1.clearSessionStorage;
exports.removeFromLocalStorage = webStorage_1.removeFromLocalStorage;
exports.removeFromSessionStorage = webStorage_1.removeFromSessionStorage;
exports.retrieveFromLocalStorage = webStorage_1.retrieveFromLocalStorage;
exports.retrieveFromSessionStorage = webStorage_1.retrieveFromSessionStorage;
